### ISSUE TITLE
Permutations

### ISSUE THREAD

**Issue by jakejh** [InouyeLab/NetRep#28]
I'm interested in running permutations to determine if gene modules in a discovery dataset are differentially preserved between two conditions of a test dataset. In this scenario, it would be useful if permutations were either made optional (modulePreservation accepted nperm=0 and just returned the observed statistics) or if there were a built-in way to permute based on sample labels instead of node labels.

Right now I'm calling modulePreservation separately for the data from each condition using nperm=2, then only using the observed statistics, which makes the process much slower than necessary. I do this for both the true sample labels and for each random shuffling of the sample labels.

**Comment by sritchie73** [comment]
Fixed in release v1.1.0

modulePreservation will now accept nPerm=0 as an argument to directly calculate the module preservation statistics without performing the permutation test.

**Comment by jakejh** [comment]
Sweet, thanks!
